name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remote SSH Commands
        uses: fifsky/ssh-action@v0.0.6
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          pass: ${{ secrets.SSH_PASS }}
          command: |
            cd ~/projects/landing-page
            git pull origin main
            chmod +x ./run.sh
            chmod +x ./serve.sh
            which pm2
            ./run.sh
